# Generated by Django 4.1.5 on 2023-07-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("em_register", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="em_register",
            name="description",
        ),
        migrations.AddField(
            model_name="em_register",
            name="degree",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="em_register",
            name="email",
            field=models.CharField(default=2, max_length=500),
            preserve_default=False,
        ),
    ]
