# Generated by Django 4.1.5 on 2023-07-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "em_register",
            "0002_remove_em_register_description_em_register_degree_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="em_register",
            name="resume",
            field=models.FileField(default="Unknown", upload_to="resumes/"),
        ),
    ]
